# Server properties
server:
  servlet:
    context-path: /tour-api
  port: 8080

  spring:
    jpa:
      show-sql:true
      hibernate:
        default_schema:public
        ddl-auto:update
      properties:
        hibernate:
          order_inserts:true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          jdbc:
            batch_size: 50
            lob:
              non_contextual_creation:true
          temp:
            use jdbc metadata defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbd:postgresql://localhost:5432/tour-of-heroes
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
    hikari:
      idle-timeout:10000
      maximum-pool-siza: 5


